version: '3'
services:
  service-transference:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docker-transference
    restart: always
    ports:
      - 8099:8099
    networks:
      bank_network:
        aliases:
          - bank_net
networks:
  bank_network:
    name: bank_net
    external: true